# Generated by Django 4.1.7 on 2023-03-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
