# Generated by Django 4.1.7 on 2023-03-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt1', '0002_rename_username_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
